language: python
python:
  - 2.6
  - 2.7
install:
  - pip install coveralls
script:
  - nosetests --with-coverage
  - pip install git+git://github.com/abstractfactory/cquery.git
after_success:
  - coveralls